services:
  db:
    image: postgres:16
    environment:
      POSTGRES_DB: mmcs
      POSTGRES_USER: mmcs
      POSTGRES_PASSWORD: mmcs
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U mmcs -d mmcs" ]
      interval: 5s
      timeout: 5s
      retries: 20

  backend:
    build: ./backend
    env_file:
      - ./backend/.env.example
    environment:
      FLASK_APP: app
      FLASK_RUN_HOST: 0.0.0.0
      CORS_ORIGINS: "*"
      DATABASE_URL: postgresql+psycopg2://mmcs:mmcs@db:5432/mmcs
    ports:
      - "5000:5000"
    depends_on:
      db:
        condition: service_healthy

  frontend:
    build: ./frontend
    ports:
      - "5173:5173"
    depends_on:
      - backend
